version: "3.5"

services:
  app:
    container_name: "app"
    image: "ghcr.io/glpi-project/${PHP_IMAGE:-githubactions-php-apache:8.3}"
    environment:
      CODE_COVERAGE: "${CODE_COVERAGE:-false}"
    volumes:
      - type: "bind"
        source: "${APPLICATION_ROOT}"
        target: "/var/www/glpi"
      - type: "bind"
        source: "${APP_CONTAINER_HOME}"
        target: "/home/www-data"
